services:
  - type: web
    name: portfolio-hub-api
    env: python
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_SECRET_KEY
        generateValue: true
      - key: APP_DB_URL
        value: sqlite+pysqlite:///./backend/app.db
      - key: APP_CORS_ORIGINS
        value: https://michael1gledhill.github.io
      - key: APP_BOOTSTRAP_ADMIN
        value: true
      - key: APP_DEFAULT_ADMIN_USERNAME
        value: admin
      - key: APP_DEFAULT_ADMIN_PASSWORD
        value: QWERTY
      - key: APP_RESET_BOOTSTRAP_ADMIN_PASSWORD
        value: true